routes/web.php
<?php
//Auth::routes();
Route::get('/', 'HomeController@home')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::group(['prefix' => 'services/', 'name' => 'services.'], function () {
    Route::get('/electric', 'HomeController@electric')->name('electric');
    Route::get('/gas', 'HomeController@gas')->name('gas');
    Route::get('/water', 'HomeController@water')->name('water');
    Route::get('/fuel-poverty', 'HomeController@fuelPoverty')->name('fuelPoverty');
    Route::get('/telecoms', 'HomeController@telecoms')->name('telecoms');
    Route::get('/chip-and-pin', 'HomeController@chipAndPin')->name('chipAndPin');
    Route::get('/waste', 'HomeController@waste')->name('waste');
    Route::get('/business-rate-review', 'HomeController@businessRateReview')->name('businessRateReview');
    //More
//    Route::get('/solar-plus', 'HomeController@solarPlus')->name('solarPlus');
//    Route::get('/solar-max', 'HomeController@solarMax')->name('solarMax');
//    Route::get('/opti-plus', 'HomeController@optiPlus')->name('optiPlus');
//    Route::get('/opti-max', 'HomeController@optiMax')->name('optiMax');
//    Route::get('/commercial-solar', 'HomeController@commercialSolar')->name('commercialSolar');
//    Route::get('/commercial-led', 'HomeController@commercialLed')->name('commercialLed');
//    Route::get('/commercial-storage', 'HomeController@commercialStorage')->name('commercialStorage');
//    Route::get('/chp', 'HomeController@chp')->name('chp');
});
//Blog
Route::group(['as' => 'blog.'], function () {
    Route::get('blog', 'BlogController@index')->name('index');
    Route::get('blog/{slug?}/{blog}', 'BlogController@show')->name('show');
});
//Career
Route::group(['as' => 'jobs.'], function () {
    Route::get('careers', 'JobController@index')->name('index');
    Route::get('careers/{slug?}/{job}', 'JobController@show')->name('show');
    Route::post('careers/{job}', 'JobController@seeker')->name('seeker');
});
//Contact
Route::get('contact', 'ContactController@index')->name('contact');
Route::post('contact', 'ContactController@store')->name('contact.store');

Route::get('error/{error}', function ($error) {
    return view('errors.' . $error);
});
Route::view('terms','pages.terms')->name('terms');
Route::view('privacy','pages.privacy')->name('privacy');

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

class Job extends Model
{
    use Notifiable;
    use SoftDeletes;
    protected $fillable = [
        "title",
        "description",
        "requirements",
        "expecting",
        "vacancies",
        "skills",
        "active",
        "meta_title",
        "meta_description",
        "meta_keywords",
        "ends_at",
        "published_at",
        "edited_at"
    ];
    public function media()
    {
        return $this->morphMany(Media::class, 'mediable');
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function seekers()
    {
        return $this->hasMany(Seeker::class);
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use App\Job;
use App\Media;
use App\Seeker;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Alert;
use Storage;
use ImageOptimizer;
class JobController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $jobs = Job::whereActive(true)->orderby('published_at', 'DESC')->paginate(5);
        return view('jobs.index', compact('jobs'));
    }


    /**
     * Display the specified resource.
     *
     * @param $slug
     * @param Job $job
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function show($slug, Job $job)
    {
        if (!$job->active) {
            abort('404');
        }
        return view('jobs.show', compact('job'));
    }

    public function seeker(Request $request, Job $job)
    {
        $seeker = new Seeker();
        $seeker->name = $request->name;
        $seeker->email = $request->email;
        $seeker->phone = $request->phone;
        $seeker->description = $request->description;
        $seeker->job_id = $job->id;
        $seeker->save();
        if (isset($request->file)) {
            $this->UploadFile($request, $seeker);
        }
        Alert::success('Thank you, We\'ll get back to you within 48 hours', 'Your CV is Received')->persistent('Close');
        return redirect()->back();
    }

    private function UploadFile(Request $request, Seeker $seeker)
    {
        $path = $request->file('file')->store('public');
        $name = explode('/', $path)[1];
        $mime = Storage::mimeType($path);
        $media = new Media();
        $media->name = $name;
        $media->mime = $mime;
        $seeker->media()->save($media);
        if(substr($mime, 0, 5) == 'image') {
            ImageOptimizer::optimize(storage_path('app/'.$path));
        }
        return $name;
    }


}

app/Http/Controllers/Office/BlogController.php
<?php

namespace App\Http\Controllers\Office;

use App\Blog;
use App\Media;
use Auth;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;
use ImageOptimizer;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::orderBy('created_at','DESC')->paginate(25);
        return view('office.blog.index', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('office.blog.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);
        $blog = new Blog;
        $blog->title = $request->title;
        $blog->user_id = Auth::user()->id;
        $blog->save();
        return redirect()->action('Office\BlogController@edit', ['blog' => $blog]);
    }


    /**
     * @param Blog $blog
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @internal param Blog $post
     */
    public function show(Blog $blog)
    {
        return view('office.blog.show', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Blog $blog
     * @return \Illuminate\Http\Response
     * @internal param Blog $post
     * @internal param int $id
     */
    public function edit(Blog $blog)
    {
        return view('office.blog.edit', compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Blog $blog
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function update(Request $request, Blog $blog)
    {

        $this->validate($request, [
            'title' => 'required',
        ]);

        $blog->title = $request->title;
        $blog->description = $request->description;
        $blog->keywords = $request->keywords;
        $blog->meta_title = isset($request->meta_title) ? $request->meta_title : $request->title;
        $blog->meta_description = isset($request->meta_description) ? strip_tags($request->meta_description) : strip_tags(str_limit($request->description, $limit = 150));
        $blog->meta_keywords = isset($request->meta_keywords) ? $request->meta_keywords : $request->keywords;
        if (isset($request->file)) {
            $blog->cover = $this->UploadFile($request, $blog);
        }
        $blog->user_id = Auth::user()->id;
        $blog->edited_at = Carbon::now();
        $blog->save();
        return redirect()->action('Office\BlogController@show', [$blog]);
    }

    public function upload(Request $request, Blog $blog)
    {
        $name = $this->UploadFile($request, $blog);
        return asset('storage/' . $name);

    }

    private function UploadFile(Request $request, Blog $blog)
    {
        $this->validate($request, [
            'file' => 'required'
        ]);
        $path = $request->file('file')->store('public');
        $name = explode('/', $path)[1];
        $mime = \Storage::mimeType($path);
        if (substr($mime, 0, 5) == 'image') {
            ImageOptimizer::optimize(storage_path('app/' . $path));
        }
        $media = new Media();
        $media->name = $name;
        $media->mime = $mime;
        $blog->media()->save($media);
        return $name;
    }

    public function active(Request $request, Blog $blog)
    {
        $this->validate($request, [
            'active' => 'required',
        ]);
        if ($request->active) {
            $blog->active = $request->active;
            $blog->published_at = Carbon::now();
        } else {
            $blog->active = $request->active;
        }
        $blog->save();
        return redirect()->action('Office\BlogController@index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Blog $blog
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function destroy(Blog $blog)
    {
        $blog->media()->delete();
        $blog->delete();
        return redirect()->action('Office\BlogController@index');
    }

    public function preview(Blog $blog)
    {
        return view('office.blog.preview',compact('blog'));
    }
}

app/Http/Controllers/Office/ContactController.php
<?php

namespace App\Http\Controllers\Office;

use App\Contact;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = Contact::orderBy('created_at','DESC')->paginate(25);
        return view('office.contacts.index', compact('contacts'));
    }

    public function show(Contact $contact)
    {
        return view('office.contacts.show',compact('contact'));
    }

    public function bySite($site)
    {
        $contacts = Contact::where('site','like',$site.'%')->orderBy('created_at','DESC')->paginate(25);
//        return $contacts;
        return view('office.contacts.index', compact('contacts'));
    }


}

app/Http/Controllers/Office/DashboardController.php
<?php

namespace App\Http\Controllers\Office;

use Analytics;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Analytics\Period;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $period = Period::days(15);
        $data = Analytics::fetchTotalVisitorsAndPageViews($period);
        $data = $data->map(function ($item) {
            return [$item['date']->format('M d') , $item['visitors'], $item['pageViews']];
        });
        return view('office.dashboard.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Office/JobController.php
<?php

namespace App\Http\Controllers\Office;

use App\Job;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Media;
use Carbon\Carbon;
use Illuminate\Support\Str;
use ImageOptimizer;
class JobController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $jobs = Job::orderBy('created_at','DESC')->paginate(25);
        return view('office.jobs.index', compact('jobs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('office.jobs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);
        $job = new Job;
        $job->title = $request->title;
        $job->user_id = Auth::user()->id;
        $job->save();
        return redirect()->action('Office\JobController@edit', ['job' => $job]);
    }


    /**
     * @param Job $job
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @internal param Job $post
     */
    public function show(Job $job)
    {
        return view('office.jobs.show', compact('job'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Job $job
     * @return \Illuminate\Http\Response
     * @internal param Job $post
     * @internal param int $id
     */
    public function edit(Job $job)
    {
        return view('office.jobs.edit', compact('job'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Job $job
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function update(Request $request, Job $job)
    {

        $this->validate($request, [
            'title' => 'required',
        ]);

        $job->title = $request->title;
        $job->description = $request->description;
        $job->requirements = $request->requirements;
        $job->expecting = $request->expecting;
        $job->vacancies = $request->vacancies;
        $job->ends_at = Carbon::parse($request->ends_at);
        $job->meta_title = isset($request->meta_title) ? $request->meta_title : $request->title;
        $job->meta_description = isset($request->meta_description) ? strip_tags($request->meta_description) : strip_tags(str_limit($request->description, $limit = 150));
        $job->meta_keywords = $request->meta_keywords;
        if (isset($request->file)) {
            $job->cover = $this->UploadFile($request, $job);
        }
        $job->user_id = Auth::user()->id;
        $job->edited_at = Carbon::now();
        $job->save();
        return redirect()->action('Office\JobController@index');
    }

    public function upload(Request $request, Job $job)
    {
        $name = $this->UploadFile($request, $job);
        return asset('storage/' . $name);

    }

    private function UploadFile(Request $request, Job $job)
    {
        $this->validate($request, [
            'file' => 'required'
        ]);

        $path = $request->file('file')->store('public');
        $name = explode('/', $path)[1];
        $mime = \Storage::mimeType($path);
        if (substr($mime, 0, 5) == 'image') {
            ImageOptimizer::optimize(storage_path('app/' . $path));
        }
        $media = new Media();
        $media->name = $name;
        $media->mime = $mime;
        $job->media()->save($media);
        return $name;
    }

    public function active(Request $request, Job $job)
    {
        $this->validate($request, [
            'active' => 'required',
        ]);

        if ($request->active) {
            $job->active = $request->active;
            $job->published_at = Carbon::now();
        } else {
            $job->active = $request->active;
        }
        $job->save();
        return redirect()->action('Office\JobController@index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Job $job
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function destroy(Job $job)
    {
        $job->media()->delete();
        $job->delete();
        return redirect()->action('Office\JobController@index');
    }

    public function preview(Job $job)
    {
        return view('office.jobs.preview', compact('job'));
    }
}

resources/views/office/jobs/create.blade.php
@extends('office.layouts.app')
@section('content')
    @component('office.components.page-title',['title'=>'Jobs Create','links'=>['Jobs'=>'office.jobs.index','Create'=>'#']])
    @endcomponent
    <div id="content" class="padding-20">
        <div class="panel-heading panel-heading-transparent">
            <strong>Create New Job Post</strong>
        </div>
        <div class="panel-body">
            @component('office.components.create-form',['route'=>'office.jobs.store'])
            @endcomponent
    </div>
@endsection

resources/views/office/jobs/index.blade.php
@extends('office.layouts.app')
@section('content')
    @component('office.components.page-title',['title'=>'Jobs','links'=>['Job'=>'office.jobs.index','Show All'=>'#']])

        <a href="{{route('office.jobs.create')}}" class="btn btn-primary btn-sm pull-right ">Create New</a>

    @endcomponent
    <div id="content" class="padding-20">
        @component('office.components.table')
            <table class="fooTableInit" data-sorting="false">
                <thead>
                <tr>
                    <th class="foo-cell nopadding">&nbsp;</th>
                    <th>Title</th>
                    <th data-hide="s300" class="">Status</th>
                    <th data-hide="s300" class="">Applied</th>
                    <th data-hide="s300,s600" class="">Ends<br> Date</th>
                    <th data-hide="all" class="">Published<br> Date</th>
                    <th data-hide="all" class="">Created<br> Date</th>
                    <th data-hide="s300" class="">Action<br> Edit</th>
                    <th data-hide="s300,s600" class="">Creator</th>

                </tr>
                </thead>
                <tbody>
                @foreach($jobs as $job)
                    <tr>
                        <td class="foo-cell">&nbsp;</td>
                        <td>
                            <a href="{{route('office.jobs.show',[$job])}}">{!! $job->title !!}</a>
                        </td>
                        <td>
                            @if($job->active)
                                <span class="label label-success">Active</span>
                            @else
                                <span class="label label-default">Inactive</span>
                            @endif

                        </td>
                        <td><a href="{{route('office.jobs.seekers.index',[$job])}}" class="btn btn-default btn-xs inline" title="show applied"> {{count($job->seekers)}}</a></td>
                        <td>
                            {{$job->published_at != null ? date('d M, Y h:m a', strtotime($job->ends_t)) : '-NaN-'}}
                        </td>
                        <td>
                            {{$job->published_at != null ? date('d M, Y h:m a', strtotime($job->published_at)) : '-NaN-'}}
                        </td>
                        <td>
                            {{$job->created_at != null ? date('d M, Y h:m a', strtotime($job->created_at)) : '-NaN-'}}
                        </td>
                        <td>
                            <form action="{{ route('office.jobs.active',[$job]) }}" method="POST">
                                {{ csrf_field() }}
                                @if($job->active)
                                    <input type="hidden" name="active" value="0">
                                    <input type="submit" value="De-activate" class="btn btn-default btn-xs ">
                                @else
                                    <input type="hidden" name="active" value="1">
                                    <input type="submit" value="Activate" class="btn btn-default btn-xs ">
                                @endif
                                <a href="{{ route('office.jobs.edit',[$job]) }}" class="btn btn-default btn-xs inline"><i
                                            class="fa fa-edit white"></i>
                                    Edit </a>
                                <a href="{{ route('office.jobs.destroy',[$job]) }}" class="btn btn-default btn-xs inline"
                                   onclick="event.preventDefault();
                                           document.getElementById('delete-task-{{ $job->id }}').submit();">
                                    <i class="fa fa-times white"></i>Delete
                                </a>
                            </form>



                            <form id="delete-task-{{ $job->id }}"
                                  action="{{ route('office.jobs.destroy',[$job]) }}" method="POST"
                                  style="display: none;">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                            </form>


                        </td>
                        <td>{!! $job->user->name !!}</td>

                    </tr>
                @endforeach
                </tbody>
            </table>
            {{$jobs->links()}}
        @endcomponent
    </div>
@endsection

resources/views/office/jobs/preview.blade.php
@extends('layouts.app')
@section('content')
    @component('components.page-title',['title'=>'Career','links'=>['Career'=>'career',$job->title=>'#']])
    @endcomponent
    <section class="padding-xxs">
        <div class="container">
            <div class="row">

                <div class="col-md-7 col-sm-7">
                    <div class="heading-title heading-border-bottom heading-color">
                        <span class="pull-right text-muted">{{$job->vacancies}} available</span>
                        <h2 class="size-20"><span>0{{$job->id}}.</span> {!! strtoupper($job->title) !!}</h2>
                    </div>
                    <div class="margin-bottom-80">
                        {!! $job->description !!}
                        <h5>REQUIREMENTS</h5>
                        <div class="requirements">
                            {!! $job->requirements !!}
                        </div>
                        <h5>WHAT WE EXPECT?</h5>
                        <div class="expecting">
                            {!!$job->expecting !!}
                        </div>

                        <a href="#careers-apply" class="btn btn-3d btn-teal scrollTo" data-offset="150"><i
                                    class="fa fa-check"></i> APPLY NOW</a>
                    </div>
                </div>

                <div class="col-md-5 col-sm-5">
                    <div class="heading-title heading-border-bottom">
                        <h2 class="size-20">APPLY NOW</h2>
                    </div>
                    <form action="{{route('jobs.seeker',[$job])}}" method="post" class="parsley" id="careers-apply"
                          enctype="multipart/form-data" >
                        <fieldset disabled>
                            <!-- required [php action request] -->
                            {{csrf_field()}}
                            <div class="row">
                                <div class="col-md-12 col-sm-12">
                                    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                                        <label>Full Name *</label>
                                        <input type="text" name="name" value="{{ old('name') }}"
                                               class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group {{ $errors->has('email') ? ' has-error' : '' }}">
                                        <label for="email">E-mail Address *</label>
                                        <input type="email" value="{{ old('email') }}" class="form-control" name="email"
                                               id="email" required>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group {{ $errors->has('phone') ? ' has-error' : '' }}">
                                        <label for="phone">Phone *</label>
                                        <input type="number" value="{{ old('phone') }}" class="form-control"
                                               name="phone"
                                               id="phone" required>
                                    </div>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-md-12 col-sm-12">
                                    <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">

                                        <label>Experience *</label>
                                        <textarea name="description" rows="4"
                                                  class="form-control" required>{{old('description')}}</textarea>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label>
                                            File Attachment
                                            <small class="text-muted">Curriculum Vitae - optional</small>
                                        </label>
                                        <!-- custom file upload -->
                                        <div class="fancy-file-upload fancy-file-primary">
                                            <i class="fa fa-upload"></i>
                                            <input type="file" class="form-control" name="file" accept="image/jpeg,application/zip,image/png,application/pdf"
                                                   onchange="jQuery(this).next('input').val((this.value).replace(/C:\\fakepath\\/i, ''));"/>
                                            <input type="text" class="form-control" placeholder="no file selected"
                                                   readonly=""/>
                                            <span class="button">Choose File</span>
                                        </div>
                                        <small class="text-muted block">Max file size: 10Mb (pdf/jpg/png)</small>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <div class="row">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-3d btn-teal btn-xlg btn-block margin-top-30">
                                    SEND APPLICATION
                                    <span class="block font-lato">We'll get back to you within 48 hours</span>
                                </button>
                            </div>
                        </div>
                    </form>
                    <hr class="margin-top-60"/>

                </div>
                <div class="col-md-12">
                    <div class="divider divider-dotted">
                    </div>
                </div>

            </div>
        </div>
    </section>
@endsection
@section('script')
    <script>
        $('ul').addClass("list-unstyled list-icons");
        $('.requirements>ul>li').append('<i class="fa fa-check"></i>');
        $('.expecting>ul>li').append('<i class="fa fa-plus-square"></i>');
    </script>
@endsection

resources/views/office/jobs/show.blade.php
@extends('office.layouts.app')
@section('content')
    @component('office.components.page-title',['title'=>'Jobs Edit','links'=>['Jobs'=>'office.jobs.index','Preview'=>'#']])
    @endcomponent
    <div id="content" class="padding-20">
        <div class="panel panel-default">
            <div class="panel-heading panel-heading-transparent">
                <strong>Job Preview <small class="text-muted">This is only sample view for reading purpose</small></strong>
            </div>
            <div class="panel-body padding-0">
                <iframe  src="{{route('office.jobs.preview',[$job])}}" style="height: 100vh; width: 100%;"></iframe>
            </div>
        </div>
    </div>
@endsection